<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
            "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>MILE.fm admin</title>
	
	<link rel="stylesheet" href="/template/<?php echo $action->theme; ?>/css/style.css" type="text/css" media="screen" />
	
	<script language="javascript" type="text/javascript" src="/js/jquery-1.2.6.js"></script>
	
	<?php echo $scripts; ?>
	
</head>

<body>

<div class="mainContent">
	<?php echo $viewHtml; ?>
	
	<div class="push"></div>
</div>

<div id="footer">
	&copy; <?php echo date('Y' ); ?> r: <?php echo $rendertime; ?> seconds
</div>

</body>
</html>
