<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

	<title>MILE fm - one square mile of visual intrigue at 72 dpi</title>
	
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	
	<link rel="alternate" type="application/rss+xml" title="RSS Feed for Square Mile Web (Recently Added)" href="<?= HTTPROOT; ?>rss/" />
	<link rel="shortcut icon" href="/favicon.ico" />
	
	<link href="/template/main/css/mile.css?<?= VERSION; ?>" rel="stylesheet" type="text/css" />
	<link href="/template/main/css/cpanel.css?<?= VERSION; ?>" rel="stylesheet" type="text/css" />
	<link href="/template/main/css/forms.css?<?= VERSION; ?>" rel="stylesheet" type="text/css" />
	<link href="/template/main/css/style.css?<?= VERSION; ?>" rel="stylesheet" type="text/css" />
</head>

<body id="body">
<?= $viewHtml; ?>
</body>

<script language="javascript" type="text/javascript" src="/js/core.js?<?= VERSION; ?>"></script>
<script language="javascript" type="text/javascript" src="/js/cpanel.js?<?= VERSION; ?>"></script>
<script language="javascript" type="text/javascript" src="/js/mile.js?<?= VERSION; ?>"></script>

<script language="javascript" type="text/javascript" src="/js/jquery-1.2.6.js"></script>
<script language="javascript" type="text/javascript" src="/js/jquery-ui-personalized-1.6rc2.js"></script>  

<? /*
<script language="javascript" type="text/javascript" src="js/jquery-1.3.1.js"></script>
<script language="javascript" type="text/javascript" src="js/jquery-ui-personalized-1.6rc5.js"></script>  
*/ ?>   
  
<script type="text/javascript">
	var $j = jQuery.noConflict();
</script>

<script language="javascript" type="text/javascript" src="/js/init.js?<?= VERSION; ?>"></script>

<? if (!ISDEV): ?>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-1160347-13");
pageTracker._trackPageview();
</script>
<? endif; ?>

</html>
